### ISSUE TITLE
Natural ids

### ISSUE THREAD

**Issue by m-gl** [cmsdaq/DAQAggregator#13]
- natural id's will be stored in the same manner across all objects - '@id' field
- to avoid id conflicts we add prefix with type of object to each id (e.g. conflict SCAL as subsystem and ttcpartition name)
- FRLs id is combination of 2 elements: FRLPc.hostname + FRL.geoSlot
- FMM id is combination of 2 elements: FMMApplication.hostname + FMM.geoslot
- SubFEDBuilder id is combination of 2 elements: TTCPartition.name + FEDBuilder.name

**Comment by ghost** [comment]
A comment on the last one: 
Shouldn't the second element of the SubFEDBuilder's identification be FRLPc.hostname instead of FEDBuilder.name ?

**Comment by m-gl** [comment]
From the mapping point of view they are equally good candidates. Do you see a reason why we should use FRLPc.hostname over FEDBuilder.name?

**Comment by ghost** [comment]
I think (better to doublecheck) that two subfedbuilders under a fedbuilder may also share a ttc partition, so this would not yield unique identification.

**Comment by Phil2812** [comment]
Yes, according to Hannes this might happen, that is why he suggested using the FRLPc's hostname. In case the FRLPc is null (we are still not sure if this case is relevant), we should have some sort of fallback in place, like using the TTC partition's name and a sequential number. Or we just assume it will never happen more than once for the same TTCP for now and discuss it again once Hannes is back.

**Comment by ghost** [comment]
A sequential number sounds good, but in the first version I would assume it does not happen and leave it as simple as possible, run it in production for some time and log for the case it happens.

**Comment by Phil2812** [comment]
Well, if it does happen and we do not handle the case properly, no snapshot for the affected HWCfg can be persisted. I have never seen this in production, but the aggregator is also intended to be used in other setups. I am fine with taking care of it later, as long as one of you remembers to do so if the case turns out to be relevant at all.

**Comment by ghost** [comment]
Current natural ids implementation (without yet considering a handling of the case above):

BU: "BU_"+buHostname
RU: "RU_"+ruHostname
FRLPc: "FRPLC_"+frlpcHostname
FED: "FED_"+fedHwcfgDBid
FMM: "FMM_"+fmmHwcfgDBid
SubSystem: "SS_"+subSysName
TTCPartition: "TTCP_"+ttcpName
FMMApplication: "FMMA_"+fmmAppHostname
FEDBuilder: "FEDB_"+fedbuilderName
SubFEDBuilder: "SFB_"+ttcpName+"$"+frlpcHostname
FRL: "FRL_"+frlGeoslot+"$"+frlpcHostname

For the FMM I preferred to use the hwcfgdb id field because it can have null reference to FMMApplication, as well as to TTCPartition.

After checking some more persistence snapshots produced (in combination with bugfixes done in the model mapping side as well), it can be used. A compatible version of JSON parser will also be written for use by the DAQView's model reconstruction.

[As of 21/7/16, the change above is not yet merged in production]
