### ISSUE TITLE
Trigger rate in FEDBuilderSummary calculation problem

### ISSUE THREAD

**Issue by m-gl** [cmsdaq/DAQAggregator#33]
Trigger rate is wrong. For example in 280296 we were running with 106 kHz. Expert shows below 100 (bottom chart)

See it here: http://daq-expert.cms:8080/DAQExpert-1.3.3/?start=2016-09-07T15:00:00+02:00&end=2016-09-07T16:00:00+02:00

Masked RUs should not take part in calculation
Also check EVB

**Comment by andreh12** [comment]
to add my two cents: for the trigger rate, using the event counts from a single RU should be sufficient. 

Because if the trigger rate drops to zero on one RU event building will stop very quickly (a similar argument holds if a RU would build events at a lower rate). The difference in processed events must be stored in buffers which can typically only hold events for a second or less.

The DaqDoctor used one of the following partitions (highest priority first):
- GTPe
- GTUP
- CPM-PRI
- GT (probably obsolete now)

CPM-PRI is typically the EVM as far as I understood.

**Comment by mommsen** [comment]
I think the safest would be to use the event rate of the EVM (eventRate in Hz in the EVM flashlist). The EVM is guaranteed to be in any run. The EVM calculates the rate as average over the last 60s.

Remi

**Comment by andreh12** [comment]
Is it actually an average over the last 60 seconds ? That may not be suitable to detect a sudden stop of event building in my opinion. 

I see that there is also an `eventCount` column in the EVM flashlist from which the rate could be calculated with smaller delay if necessary.

**Comment by mommsen** [comment]
Hi Andre,

it's actually averaged over the last 1 second. Too many EvB performance measurements (which average the point over 60s) in the last couple of days....

Remi

**Comment by ghost** [comment]
Fixed, according to Remi's suggestion.

Thanks,
Michail
