### ISSUE TITLE
Items to add to the data model

### ISSUE THREAD

**Issue by hsakulin** [cmsdaq/DAQAggregator#38]
- Dead time, dead time beam active, dead time from other sources 
  FROM:  tcds_cpm_deadtimes  (updated only once per LS ?)
- Trigger rate from physics, randoms, calibration; suppressed trigger rate 
  FROM: tcds_cpm_rates  (updated only once per LS ?)
- num triggers / num suppressed triggers
  FROM: tcds_cpm_counts
- Current prescale column 
  FROM: probably in a trigger flash list?
- Number of resyncs
  FROM: tcds_pm_action_count ?
- Fill number
  FROM: tcds_cpm_deadtimes
- TCDS action founts
  FROM: tcds_pm_action_counts
- Instantaneous luminosity
  FROM: ?
- CMS Magnet current
  FROM: ?

**Comment by andreh12** [comment]
instantaneous luminosity could probably be taken from cmswbm, /cmswbm/cmsdb/servlet/LumiScalers?FORMAT=XML

**Comment by andreh12** [comment]
fill number is in /cmswbm/cmsdb/servlet/LhcMonitor?FORMAT=XML on cmswbm as text content of element /Monitor/LhcSample/FILLN

**Comment by andreh12** [comment]
I saw that e.g the `tcds_cpm_counts` and `tcds_cpm_rates`  flashlists have a fill number column (see also cmsdaq/DAQExpert/issues/10 )

**Comment by ghost** [comment]
Would it also make sense to include section number regarding the items of the first three bullets?
If yes, does it make any difference if this is taken from either one of the three cpm flashlists (rates, counts, deadtimes) or it's safe to assume that these three refer to the same LS at a given moment?

**Comment by andreh12** [comment]
since retrieving different flashlists will never happen exactly at the same time (and there may also be different delays in the processing which happens before they arrive on the LAS) the lumi section numbers can be different when the different flashlists are retrieved (most of the time they will be the same).

Personally I find an update interval of the duration of a lumi section much too long (shifters may see alarms which come one lumi section later as false alarms if the problem has disappeared in the mean time) so we should probably try to find out if there is a reason why these flashlists can not be updated once per second or so. If that is impossible, I would vote for using the json returned by the /update URL of the CPM application instead (but this is a big json text).

**Comment by ghost** [comment]
Thanks. I also think we should see whether the values can and/or makes sense to be updated more frequently. For the time being I would suggest adding the three section numbers associated with these values, so that it will, in the future, be possible to associate the values with the lumi section they belong to (as recorded on the LAS, at least), if needed.
Where can I find this CPM application ?
