### ISSUE TITLE
support for uTCA FED TTS states 

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQAggregator#85]
these are only available through the TCDS system. The code should do the following:

- find (C/L)PM url from tcdsFM
- look up PM in HWCfgDB
- find attached PIs
- match PI flash list context + service with PI attached to PM
- a masked channel has flag 0x98 = 152

**Comment by m-gl** [comment]
I've implemented this in branch feature/mtca-feds. Will be released soon to 1.13.0. I'm still waiting for more test cases, more specifically when there will be more uTCA Feds in the run - so far I have test case with only 45 feds. For this I need to download the flashlists to use them in tests. Currently we are not persisting flashlists due to full area for flashlists on filer. This makes things more difficult as I can turn on flashlist persistence only for short period of time. Otherwise area will be get full.

**Comment by andreh12** [comment]
run 296075 during the weekend was a relatively long run, a corresponding snapshot is `2017/6/5/1/1496624402023.smile`. I count 156 FEDids >= 1024 and < 10000 .

**Comment by m-gl** [comment]
Seems like there is no more requests related to uTCA FEDS and no problems were reported since it's deployed in production last Tuesday. Closing the issue.
